server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 1000 #dev only
    eviction-interval-timer-in-ms: 1000 #dev only
spring:
  application:
    name: poc-registry

ribbon:
  ServerListRefreshInterval: 500 #dev only
  ReadTimeout: 60000