spring:
  application:
    name: poc-document
  datasource:
    url: jdbc:mysql://192.168.99.100/axon-poc
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: kyc
    prefer-ip-address: true
    lease-renewal-interval-in-seconds:  1 #dev only
    lease-expiration-duration-in-seconds:  2 #dev only
  client:
    registerWithEureka: true
    registry-fetch-interval-seconds: 1 #dev only
    service-url:
      defaultZone: http://kyc:8761/eureka
    healthcheck:
      enabled: true

ribbon:
  ServerListRefreshInterval: 500 #dev only
  ReadTimeout: 60000

server:
  port: 0

axon:
  distributed:
    enabled: true

#logging:
#  level:
#    org.axonframework: DEBUG
